station:
  name: "Test_station"

camera:
  index: 0

scanner:
  device: "/dev/input/by-id/usb-Datalogic_ADC_Inc._Handheld_Barcode_Scanner-event-kbd"

storage:
  local_directory: "/home/admin/Production_Photos"

azure:
  enabled: false
  storage_account: ""
  container: "photos/production"
  tenant_id: ""
  client_id: ""
  client_secret: ""
